name: axe
on: pull_request
jobs: 
  axe:
    runs-on: self-hosted
    steps: 
    - uses: actions/checkout@v2
    - name: Use NodeJS 12.x
      uses: actions/setup-node@v1
      with: 
        node --version: 12.x
    - run: npm ci
    - run: npm run start & npx wait-on  https://localhost:3000
    - name: Run Axe
      run: | 
        npm install -g @axe/core/cli
        axe https://localhost:3000 --exit